### PR TITLE
Add possibility to use as hours-only timer

### PR DESCRIPTION
**Pull request by michaelkowalski**
In a project I'm working on we only need something like HH:MM:SS. When we set the timer to 2 days, it was displaying 23:59:59 etc.

I can make a more generic solution if you have some ideas.

### CODE REVIEW

**Comment by qq3094128766** [comment]
@michaelkowalski thank you, i hope @talalmajali merge pull requests, This is very practical,  I have such a need #68

**Comment by IkaroAlef** [comment]
It'll be great if this solution were extended to all parts of timer.

**Comment by michaelkowalski** [comment]
Oh, sorry guys! Didn't check responses here. Are you still in need of something like that? If yes, please mention me I'll then get a notification 😅

**Comment by Nazim-hasan** [comment]
@michaelkowalski Could you please have a look into this? We need this feature. 
CC: @talalmajali

**Pull request closed without merging**
