### PR TITLE
Add a class field to hold the lifecycle state of the component and Update componentWillReceiveProps to componentDidUpdate

### PR DESCRIPTION
**Pull request by jhainaua**
Add _isMounted to handle async requests while CountDown is unmounted.

### CODE REVIEW

**Comment by dsernst** [comment]
It's a little difficult to review this PR for its stated goals, because of all the whitespace changes.

Can those be separated out into a different PR?

**Comment by jhainaua** [comment]
I don't have time to address this today or Tuesday. I'll have time to post a revised PR by Wednesday or Thursday. In the meantime; for anyone else who might be having some trouble locating the changes please see my notes below. Thank you for your patience.

1. Ctrl-f or Cmd-f for the _isMounted variable. 
2. Compare the lifecycle methods.  

NEW CODE: componentDidMount, componentWillUnmount, componentDidUpdate. 

vs.

EXISTING CODE: componentDidMount, componentWillUnmount, componentWillReceiveProps

**Comment by talalmajali** [comment]
@jhainaua what's the goal of tracking the lifecycle in the `_isMounted` variable?

**Comment by talalmajali** [comment]
@jhainaua @kenmistry @dsernst i've upgraded the component to use the component did mount, please upgrade to `2.7.1`

**Pull request closed without merging**
